site_name: ARIA AI Agents
site_description: Documentation for ARIA AI Agents
site_author: TheBlockRhino

# The docs directory (where your .md files live)
docs_dir: docs

# Build directory (where MkDocs will output the static site)
site_dir: site

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
  logo: assets/images/logo.png

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ARIADevHub/aria_ai_agents
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ARIA_AI_AGENTS

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_py_pages.py
        - scripts/gen_ref_yaml_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - include-markdown
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            show_root_heading: true
          docstring_style: google

nav:
  - Home: index.md 
  - ARIA CLI Usage Guide: cli-guide.md
  - How-to Guides: how-to-guides.md  
  - AI Tutorial: tutorials.md
  - LLMS Explained: about-llms.md
  - ARIA AI Agents: explanation.md  
  - Resources: resources.md
  - API Reference: api/
  - Prompt Reference:
    - Prompts:
        - Prompt Chaining: yaml/prompts/prompt_chaining.md
    - Templates:
        - Agent Template: yaml/templates/agent_template.md
        - Episode Template: yaml/templates/episode_template.md
        - Season Template: yaml/templates/season_template.md
        - Tracker Template: yaml/templates/tracker_template.md
    

copyright: |
  &copy; 2024 <a href="https://github.com/ARIADevHub"  target="_blank" rel="noopener">ARIADevHub</a>
