# Docs workflow
# Deploy documentation to GitHub Pages
# What It Does
# - Triggers on push and pull requests to main.
# - Installs mkdocs-material (which pulls in mkdocs).
# - Runs mkdocs gh-deploy --force, pushing the built docs to the gh-pages branch.
# - Make sure GitHub Pages is enabled and set to use the gh-pages branch.

name: Docs

on:
  push:
    branches: 
      - master
      - main
# Allows pushing to gh-pages
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/cache@v2
        with:          
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
