# Tests workflow
# What It Does
# - Triggers on push and pull requests to the main branch.
# - Checks out your code.
# - Sets up Python 3.x.
# - Installs dependencies from requirements.txt if it exists.
# - Runs ARAI AI Agents test suite with pytest if there’s a tests/ folder.

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the code
      - uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4. Run tests
      - name: Run tests
        run: |
          # If you have a tests/ folder
          if [ -d tests ]; then
            python -m pytest
          else
            echo "No tests directory found, skipping tests."
          fi
